# Generated by Django 5.2.7 on 2025-10-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full name')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact number')),
                ('persons', models.PositiveSmallIntegerField(default=1, verbose_name='Number of persons')),
                ('travel_start_date', models.DateField(verbose_name='Travel start date')),
                ('travel_end_date', models.DateField(verbose_name='Travel end date')),
                ('description', models.TextField(blank=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=20)),
            ],
        ),
    ]
